name: "mnist"
platform: "tensorflow_savedmodel"
max_batch_size: 5
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 28, 28, 1 ]
  }
]
output [
  {
    name: "output_1"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]