environment_name       = "dev"
environment_project_id = "YOUR_PROJECT_ID"
git_namespace          = "YOUR_GIT_NAMESPACE"
git_user_email         = "YOUR_GIT_USER_EMAIL"
git_user_name          = "YOUR_GIT_USER_NAME"
