import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./components/Menu"

const inter = Inter({ subsets: ["latin"] });
export const dynamic = 'force-dynamic'
export const metadata: Metadata = {
  title: "Online Boutique AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-10">
      <div className="min-h-screen  ">
      <header className="border-b-2 border-neutral">
                  <div className="flex container mx-auto">
                  <Menu />
                    </div>
                </header>
        
                <main
                  role="main"
                  className="w-full sm:w-2/3 md:w-3/4 pt-1 px-2"
                >
        
        {children}
        </main>
        </div>
        </body>
    </html>
  );
}
