# coding: utf-8

"""
    sdk.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.game_server_object_meta import GameServerObjectMeta  # noqa: E501
from swagger_client.rest import ApiException


class TestGameServerObjectMeta(unittest.TestCase):
    """GameServerObjectMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGameServerObjectMeta(self):
        """Test GameServerObjectMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.game_server_object_meta.GameServerObjectMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
