# coding: utf-8

# flake8: noqa
"""
    sdk.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.game_server_object_meta import GameServerObjectMeta
from swagger_client.models.game_server_spec import GameServerSpec
from swagger_client.models.game_server_spec_health import GameServerSpecHealth
from swagger_client.models.googlerpc_status import GooglerpcStatus
from swagger_client.models.protobuf_any import ProtobufAny
from swagger_client.models.sdk_duration import SdkDuration
from swagger_client.models.sdk_empty import SdkEmpty
from swagger_client.models.sdk_game_server import SdkGameServer
from swagger_client.models.sdk_game_server_status import SdkGameServerStatus
from swagger_client.models.sdk_key_value import SdkKeyValue
from swagger_client.models.status_address import StatusAddress
from swagger_client.models.status_counter_status import StatusCounterStatus
from swagger_client.models.status_list_status import StatusListStatus
from swagger_client.models.status_player_status import StatusPlayerStatus
from swagger_client.models.status_port import StatusPort
from swagger_client.models.stream_result_of_sdk_game_server import StreamResultOfSdkGameServer
