# coding: utf-8

"""
    sdk.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class GameServerSpecHealth(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'disabled': 'bool',
        'period_seconds': 'int',
        'failure_threshold': 'int',
        'initial_delay_seconds': 'int'
    }

    attribute_map = {
        'disabled': 'disabled',
        'period_seconds': 'period_seconds',
        'failure_threshold': 'failure_threshold',
        'initial_delay_seconds': 'initial_delay_seconds'
    }

    def __init__(self, disabled=None, period_seconds=None, failure_threshold=None, initial_delay_seconds=None, _configuration=None):  # noqa: E501
        """GameServerSpecHealth - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._disabled = None
        self._period_seconds = None
        self._failure_threshold = None
        self._initial_delay_seconds = None
        self.discriminator = None

        if disabled is not None:
            self.disabled = disabled
        if period_seconds is not None:
            self.period_seconds = period_seconds
        if failure_threshold is not None:
            self.failure_threshold = failure_threshold
        if initial_delay_seconds is not None:
            self.initial_delay_seconds = initial_delay_seconds

    @property
    def disabled(self):
        """Gets the disabled of this GameServerSpecHealth.  # noqa: E501


        :return: The disabled of this GameServerSpecHealth.  # noqa: E501
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled):
        """Sets the disabled of this GameServerSpecHealth.


        :param disabled: The disabled of this GameServerSpecHealth.  # noqa: E501
        :type: bool
        """

        self._disabled = disabled

    @property
    def period_seconds(self):
        """Gets the period_seconds of this GameServerSpecHealth.  # noqa: E501


        :return: The period_seconds of this GameServerSpecHealth.  # noqa: E501
        :rtype: int
        """
        return self._period_seconds

    @period_seconds.setter
    def period_seconds(self, period_seconds):
        """Sets the period_seconds of this GameServerSpecHealth.


        :param period_seconds: The period_seconds of this GameServerSpecHealth.  # noqa: E501
        :type: int
        """

        self._period_seconds = period_seconds

    @property
    def failure_threshold(self):
        """Gets the failure_threshold of this GameServerSpecHealth.  # noqa: E501


        :return: The failure_threshold of this GameServerSpecHealth.  # noqa: E501
        :rtype: int
        """
        return self._failure_threshold

    @failure_threshold.setter
    def failure_threshold(self, failure_threshold):
        """Sets the failure_threshold of this GameServerSpecHealth.


        :param failure_threshold: The failure_threshold of this GameServerSpecHealth.  # noqa: E501
        :type: int
        """

        self._failure_threshold = failure_threshold

    @property
    def initial_delay_seconds(self):
        """Gets the initial_delay_seconds of this GameServerSpecHealth.  # noqa: E501


        :return: The initial_delay_seconds of this GameServerSpecHealth.  # noqa: E501
        :rtype: int
        """
        return self._initial_delay_seconds

    @initial_delay_seconds.setter
    def initial_delay_seconds(self, initial_delay_seconds):
        """Sets the initial_delay_seconds of this GameServerSpecHealth.


        :param initial_delay_seconds: The initial_delay_seconds of this GameServerSpecHealth.  # noqa: E501
        :type: int
        """

        self._initial_delay_seconds = initial_delay_seconds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GameServerSpecHealth, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GameServerSpecHealth):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GameServerSpecHealth):
            return True

        return self.to_dict() != other.to_dict()
