# coding: utf-8

"""
    sdk.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class SdkGameServer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'object_meta': 'GameServerObjectMeta',
        'spec': 'GameServerSpec',
        'status': 'SdkGameServerStatus'
    }

    attribute_map = {
        'object_meta': 'object_meta',
        'spec': 'spec',
        'status': 'status'
    }

    def __init__(self, object_meta=None, spec=None, status=None, _configuration=None):  # noqa: E501
        """SdkGameServer - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._object_meta = None
        self._spec = None
        self._status = None
        self.discriminator = None

        if object_meta is not None:
            self.object_meta = object_meta
        if spec is not None:
            self.spec = spec
        if status is not None:
            self.status = status

    @property
    def object_meta(self):
        """Gets the object_meta of this SdkGameServer.  # noqa: E501


        :return: The object_meta of this SdkGameServer.  # noqa: E501
        :rtype: GameServerObjectMeta
        """
        return self._object_meta

    @object_meta.setter
    def object_meta(self, object_meta):
        """Sets the object_meta of this SdkGameServer.


        :param object_meta: The object_meta of this SdkGameServer.  # noqa: E501
        :type: GameServerObjectMeta
        """

        self._object_meta = object_meta

    @property
    def spec(self):
        """Gets the spec of this SdkGameServer.  # noqa: E501


        :return: The spec of this SdkGameServer.  # noqa: E501
        :rtype: GameServerSpec
        """
        return self._spec

    @spec.setter
    def spec(self, spec):
        """Sets the spec of this SdkGameServer.


        :param spec: The spec of this SdkGameServer.  # noqa: E501
        :type: GameServerSpec
        """

        self._spec = spec

    @property
    def status(self):
        """Gets the status of this SdkGameServer.  # noqa: E501


        :return: The status of this SdkGameServer.  # noqa: E501
        :rtype: SdkGameServerStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this SdkGameServer.


        :param status: The status of this SdkGameServer.  # noqa: E501
        :type: SdkGameServerStatus
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SdkGameServer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SdkGameServer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SdkGameServer):
            return True

        return self.to_dict() != other.to_dict()
