# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM us-central1-docker.pkg.dev/ai-on-gke/rag-on-gke/frontend@sha256:8f40b9485739fb2b2b4d77e18f101e1030abff63d4a6240c4cfbf2c333b593fc
RUN pip install langchain-google-cloud-sql-pg==0.1.0
RUN pip install langchain-google-vertexai==0.1.1
#RUN pip install langchain-community==0.0.29
#RUN pip install huggingface_hub

ADD ./ /workspace/frontend
WORKDIR /workspace/frontend

CMD ["python", "main.py"]
